feat(once_cell): remove dependency on once_cell
eza-community/eza pull request #1181
Opened 2024-10-06 08:46 UTC by erwinvaneijk

Rust 1.80 has a proper implementation of LazyLock, which, when used, removes the dependency on once_cell.

- update toolchain to 1.80.0 from 1.70.0
- remove once_cell from dependencies

Fixes: #1169

2024-10-06 09:17 UTC, cafkafk requested changes
> update toolchain to 1.80.0 from 1.70.0

I'm not sure we can just do that this easily, we need to ensure that it still supports most distros, specially debian tends to be quite slow here.

2024-10-06 17:06 UTC, erwinvaneijk commented
> > update toolchain to 1.80.0 from 1.70.0
> 
> I'm not sure we can just do that this easily, we need to ensure that it still supports most distros, specially debian tends to be quite slow here.

Agreed, but I figured it would be convenient to see where things would break down if the migration actually should happen.

2025-04-07 19:36 UTC, ariasuni commented
Well, [Debian testing is now at 1.85.0](https://packages.debian.org/search?suite=trixie&searchon=names&keywords=rust), so I suppose it’s safe to go to 1.80. Anyway, either it’s the distro packaging a new version of eza but then it’ll use a newer version of Rust, or using a µlibc build of eza, or a user using rustup to make a custom build. right?

2025-04-10 13:44 UTC, ariasuni requested changes
Well we already use 1.81, so I think you redo your PR but removing the changes related to `.github/workflows/unit-tests.yml`, `rust-toolchain.toml`, and files in `tests/gen/`, and then we’ll be able to merge that easily.

2025-04-10 21:59 UTC, ariasuni approved these changes

2025-04-20 08:43 UTC, merged