Update: Fully update all transitive dependencies via `cargo update --recursive`
eza-community/eza pull request #1234
Opened 2024-11-14 16:59 UTC by dbast

This is maybe a controversial PR, but I found this while working on https://github.com/eza-community/eza/pull/1226

Dependabot seems to only take care of package versions in `Cargo.toml` and then only update transitive packages in `Cargo.lock` if the pinning constrains of the updated package changes. BUT dependabot never looks at all the transitive dependencies listed in the `Cargo.lock` and updating all of them to the newest version within the constrains.

Thus this PR fully updates all transitive dependencies (which is a lot) via running `cargo update --recursive` and committing that. Reveals lots of outdated versions.

Any better approach to do that? (A github workflow doing that and creating a PR every week could be one option... didn't find a way to convince dependabot to fully take care of transitive dependencies).

2024-11-15 16:14 UTC, dbast commented
One package has to be kept at an older version due to rustc 1.70.0 compatibility. Done via second commit containing the result of `cargo update -p clap@4.5.21 --precise 4.4.18`

2024-11-15 16:22 UTC, dbast commented
Ready for review :)

2024-11-16 08:46 UTC, dbast commented
Updating url only to 2.5.0 (instead of 2.5.3) massively reduces the overall PR diff from +477 -280 lines to +213 -256 by not introducing that many new transitive dependencies... full update then to be done via further PRs. Maybe that makes this more acceptable.

2024-11-22 14:55 UTC, dbast commented
The tests are passing with rust 1.70.0 by keeping clap at an older version. Anything else to be done for this PR?

2024-11-28 06:36 UTC, cafkafk requested changes
> The tests are passing with rust 1.70.0 by keeping clap at an older version. Anything else to be done for this PR?

Yes, someone needs to ensure most major distros are one 1.74, I don't think we should avoid updating clap here.

2024-11-28 16:30 UTC, dbast commented
This gives an overview https://repology.org/project/rust/versions

Traditional distros do not update packages like eza a new version (only backport security fixes), after the distro did a stable release... like Debian 12. Thus the rust version does not matter for Debian 12 (rustc 1.63.0), but for the unreleased Debian 13 (rustc 1.82.0) it would matter?

Will rebase the PR + fully updates everything + pump the MSRV to 1.74.0

2024-11-29 08:51 UTC, dbast commented
some tests on nix fail ... cause to be clarified

2024-11-29 12:16 UTC, dbast commented
rebased the PR + fully updated everything (not keeping anything on an older version) + pumped the MSRV to 1.74.0 + adapted 3 tests. 

@cafkafk this is ready for another review. thanks!

2024-12-05 19:24 UTC, closed without merging