chore: fix, add and sort icons
eza-community/eza pull request #1274
Opened 2024-12-24 07:49 UTC by Freed-Wu

Fix:

ruby's official logo is falling down: https://www.ruby-lang.org/en/about/logo/
*.com is DOS binary format: https://en.wikipedia.org/wiki/COM_file
use editorconfig logo for .editorconfig
bare metal programs also use *.lib and *.a as their static library extension
use linux icon is not appropriate
however, bare metal programs don't support dynamic library
so use windows icon for *.dll
use vim icon for _vimrc and _gvimrc, which are vimrc filename on windows
use fennel icon for .fennelrc and fennelrc

Add some missing icons from:

- https://github.com/lambdalisue/vim-nerdfont/blob/master/assets/json/extension.json
- https://github.com/lambdalisue/vim-nerdfont/blob/master/assets/json/basename.json

Sort them alphabetically

##### Description

##### How Has This Been Tested?

2024-12-28 18:57 UTC, cafkafk requested changes
thanks for the contribution, before I continue the review, please make sure the code is compiling, currently it fails due to a lack of a comma

2024-12-29 04:41 UTC, Freed-Wu commented
Sort often bring conflict when new icon is added.

2025-01-05 15:01 UTC, Freed-Wu commented
Split to
#1295
#1296
#1297
#1298
#1299
#1300
#1301
#1302
#1303
#1304
#1305
#1306
#1307
#1308
#1309
#1310
#1311
#1312
#1313
#1314
#1315
#1316
#1317

2025-05-24 06:59 UTC, closed without merging

2025-05-24 06:59 UTC, cafkafk commented
> Split to
> 
>     * [chore: add fennel icon for ~/.fennelrc and ~/.config/fennel/fennelrc #1295](https://github.com/eza-community/eza/pull/1295)
> 
>     * [chore: add vim icon for .gvimrc, _vimrc and _gvimrc #1296](https://github.com/eza-community/eza/pull/1296)
> 
>     * [chore: add MS DOS icon for *.com #1297](https://github.com/eza-community/eza/pull/1297)
> 
>     * [chore: add ruby icon for config.ru, Gemfile, Gemfile.lock, procfile, rake, rakefile and change ruby icon #1298](https://github.com/eza-community/eza/pull/1298)
> 
>     * [chore: add editorconfig icon for .editorconfig #1299](https://github.com/eza-community/eza/pull/1299)
> 
>     * [chore: add icon for Elasticsearch's files #1300](https://github.com/eza-community/eza/pull/1300)
> 
>     * [chore: add dropbox icon #1301](https://github.com/eza-community/eza/pull/1301)
> 
>     * [chore: add elixir icon for *.eex and mix.lock #1302](https://github.com/eza-community/eza/pull/1302)
> 
>     * [chore: add gcloud icon for .gcloudignore #1303](https://github.com/eza-community/eza/pull/1303)
> 
>     * [chore: add renovate icon for renovate.json #1304](https://github.com/eza-community/eza/pull/1304)
> 
>     * [chore: add clojure icon for *.cljc #1305](https://github.com/eza-community/eza/pull/1305)
> 
>     * [chore: add C++ icon for *.cuh #1306](https://github.com/eza-community/eza/pull/1306)
> 
>     * [chore: add fsharp icon for *.f# and *.fsscript #1307](https://github.com/eza-community/eza/pull/1307)
> 
>     * [chore: add markdown icon for *.mdx #1308](https://github.com/eza-community/eza/pull/1308)
> 
>     * [chore: add photoshop icon for *.psb #1309](https://github.com/eza-community/eza/pull/1309)
> 
>     * [chore: add python icon for *.pxd and *.pyx #1310](https://github.com/eza-community/eza/pull/1310)
> 
>     * [chore: add Visual Studio icon for *.suo #1311](https://github.com/eza-community/eza/pull/1311)
> 
>     * [chore: add swift icon for *.xcplayground #1312](https://github.com/eza-community/eza/pull/1312)
> 
>     * [chore: add icon for *.hrl #1313](https://github.com/eza-community/eza/pull/1313)
> 
>     * [chore: add prettier icon for *.prettierignore #1314](https://github.com/eza-community/eza/pull/1314)
> 
>     * [chore: add eslint icon for .eslintignore #1315](https://github.com/eza-community/eza/pull/1315)
> 
>     * [chore: add brew icon for brewfile and brewfile.lock.json #1316](https://github.com/eza-community/eza/pull/1316)
> 
>     * [chore: add library icon for *.a and *.lib #1317](https://github.com/eza-community/eza/pull/1317)
> 
> 
> This PR will only sort the icons.

All of the above have comments or have been merged, I think we should create a new PR to sort these after the fact, since that's much easier. Thanks for all the work so far.