feat: match folder icon to reflect contents
eza-community/eza pull request #137
Opened 2023-08-13 20:12 UTC by PThorpe92

Indicate folder state with icon #92 

I'll mark it as a draft, until everyone can agree on which folder icons to use for empty directories. 

If anyone has a better approach to the function in file.rs.. please let me know. I just started looking at the code-base today, so I could easily be missing something.

Where would you like me to include tests for this behavior? I didn't want to stuff them somewhere that it didn't appear they belong, so if someone wants to point me in the direction of where tests relevant to this would go, I will include them :+1: 

Also, perhaps the option for users to display empty folders in a different color?

2023-08-14 20:21 UTC, sbatial commented on src/fs/file.rs
> +         // . & .. are skipped, if the returned iterator has .next(), it's not empty
```suggestion
                   // . & .. are skipped, if the returned iterator has .next(), it's not empty
```

2023-08-14 20:32 UTC, sbatial requested changes

2023-08-14 20:32 UTC, sbatial commented on src/fs/file.rs
> +    }
```suggestion
    pub fn is_empty_dir(&self) -> bool {
        if self.is_directory() {
            match Dir::read_dir(self.path.clone()) {
                // . & .. are skipped, if the returned iterator has .next(), it's not empty
                Ok(has_files) => has_files.files(super::DotFilter::Dotfiles, None, false, false).next().is_none(),
                Err(_) => false,
            }
        } else {
            false
        }
    }
```

2023-08-14 20:32 UTC, sbatial commented on src/fs/file.rs
> +    }
This should fix the failing CI.
Otherwise: :+1:

2023-08-14 21:02 UTC, PThorpe92 commented
@sbatial 

I had that saved locally flipped as suggested by clippy, I just didn't want to commit it until I write the tests too. Can you point me in the direction of where I should include tests for this?

2023-08-14 23:11 UTC, sbatial commented
> I had that saved locally flipped as suggested by clippy, I just didn't want to commit it until I write the tests too.

Oh, my bad. Just force-push over it if u want

> Can you point me in the direction of where I should include tests for this?

So the tests are currently in the `xtests` folder.
We haven't gotten them to work yet.
I just looked into it a bit more and they are written with another tool by @ogham: [ogham/specsheet](https://github.com/ogham/specsheet).

I think the biggest problem right now is that no one has got the Vagrant setup up and running.
The last 'discussion' was in #117.
You could try and see if the docker setup (from https://github.com/ogham/exa/pull/1230) works on your end if you'd like

2023-08-14 23:22 UTC, PThorpe92 commented
No worries, I just didn't want people to think I was ignoring it, I just didn't want to push (again) and have the CI run, just to go back and add tests and do it again. Either way I just pulled/rebased so it's all good. 

Ah ok.. I was wondering what the state of all those vagrantfile tests was. I understand the unique situation of testing something like an LS replacement, regular unit tests won't work without being run on every imaginable filesystem. I'll take a look at the dockerfile PR and see if I can get it up and running later tonight. Thanks!

2023-08-15 02:08 UTC, mentalisttraceur commented
Fwiw I agree using closed solid folder for non-empty and open outlined folder for empty.

2023-08-15 03:06 UTC, cafkafk commented
> Fwiw I agree with closed solid folder for non-empty and open outlined folder for empty.

Having solid for contents and outlined for empty seems the most intuitive.

I think this makes sense. 

That said, if we used closed solid and closed outlined, we could have open be folders with content that isn't staged in git yet. But until (if) we actually implemented that behavior, I'd personally prefer `closed solid -> non-empty` and `open outlined -> empty`.

2023-08-15 04:25 UTC, PThorpe92 commented
Well I wasn't able to get that dockerfile from the exa PR linked above, but I will keep an eye on that branch for sure. It may be time start a discussion or issue on testing, and whether it is worth it to just start including more unit testing in a separate directory?

>  we could have open be folders with content that isn't staged in git yet.

I like that idea, I wonder if there are two different folder icons (open/closed) that have the .git logo, because that would be a nice to display. But at least could be regular subfolders inside repos.

This PR should be all set then, as the current behavior is outlined/open for empty and solid closed for non-empty.

2023-08-15 04:35 UTC, cafkafk approved these changes
> This PR should be all set then, as the current behavior is outlined/open for empty and solid closed for non-empty.

Local testing confirms this working.

![2023-08-15_06-34](https://github.com/eza-community/eza/assets/89321978/6458fa9d-30fe-4025-8c17-eb7c3e2f19c9)

LGTM :+1:

2023-08-16 15:39 UTC, merged