fix: filename escaping (last character lost sometimes, no hyperlink)
eza-community/eza pull request #163
Opened 2023-08-25 00:27 UTC by ariasuni

Follow-up of #17.
Fix #162.

Other bugs fixed/improvements:
- Take control characters outside of ASCII into account (by using [`char::is_control`](https://doc.rust-lang.org/std/primitive.char.html#method.is_control)).
- Hyperlink are now appearing on filenames with escaped characters
- Deduplicated the escaping code by replacing the original code with the optimized one (that I very slightly improved).

2023-08-25 03:20 UTC, cafkafk requested changes
I haven't had time to run this yet, but here are my immediate thoughts.

Also, how did you A/B test this?

2023-08-25 03:20 UTC, cafkafk commented on src/output/escape.rs
> +    if string.chars().all(|c| !c.is_control()) {
This is more idiomatic and elegant, nice!

2023-08-25 03:20 UTC, cafkafk commented on src/output/escape.rs
> +            // biased towards regular characters, we push control characters them immediately
Slight typo
```suggestion
            // biased towards regular characters, we push control characters immediately
```

2023-08-25 03:20 UTC, cafkafk commented on src/output/file_name.rs
> +            bits.push(ANSIString::from(format!("\x1B]8;;{}\x1B\x5C", self.file.path.display())));
`\x1B]8;;{}\x1B\x5C` is used both here and on line 318, maybe we should introduce a `const` to make the hyperlink format "magic string" easier to understand?

2023-08-25 03:20 UTC, cafkafk commented on src/output/file_name.rs
> +        bits
This is very satisfying, well done!

2023-08-25 03:20 UTC, cafkafk commented on src/output/file_name.rs
> +            bits.push(ANSIString::from(format!("\x1B]8;;{}\x1B\x5C", self.file.path.display())));
Perhaps also do a quick check if it appears in other places in the codebase?

2023-08-25 03:20 UTC, cafkafk commented on src/output/file_name.rs
> +            bits.push(ANSIString::from(format!("\x1B]8;;{}\x1B\x5C", self.file.path.display())));
Fixing this could be it's own separate commit if you'd prefer that.

2023-08-26 02:14 UTC, ariasuni commented
I added the `file:///` protocol makes the hyperlink feature works in Konsole, but then I realized it’s broken and started investigating [the spec (?)](https://gist.github.com/egmontkob/eb114294efbcd5adb1944c9f3cb5feda).

So after investigation, what needs to be done:

- URL-encode the URL to make it work for «complex» file names
- Add hostname in the URL, e.g. `file://hostname/rest/of/the/path`

I already have working code for the first item that I need to polish and push. The second one should be trivial if I use the correct crate.

2023-09-08 21:05 UTC, ariasuni commented
Note: hyperlinks don’t work in Konsole, but same as `ls`, it’s because of a [KDE bug](https://bugs.kde.org/show_bug.cgi?id=461756). It works fine in Kitty.

As said, it works even with weird file names, it fails with non-UTF-8 filenames but same as `ls`. I think it’s ready to merge.

2023-09-09 04:11 UTC, cafkafk approved these changes
My local testing of this and integration tests indicates this is working, ty for the pull request!

2023-09-09 04:11 UTC, merged