fix: canonicalize errors when the destination of a symbolic link is bad
eza-community/eza pull request #262
Opened 2023-09-11 19:42 UTC by cfxegbert

Addresses bug https://github.com/eza-community/eza/issues/255

The call `std::fs::canonicalize` is documented to error when the destination of a symbolic is bad.  Could not write an xtest because my development machine can not run Vagrant.

2023-09-11 21:02 UTC, PThorpe92 requested changes

2023-09-11 21:31 UTC, cfxegbert commented on src/fs/file.rs
> +    // TODO: Resolving an absolute path can be an expensive call.  We only
It was only being used internally.  Started changing it to a OnceCell to do a on-demand calculation but decided to do it in a separate pull request.

2023-09-11 21:34 UTC, PThorpe92 commented on src/fs/file.rs
> +    // TODO: Resolving an absolute path can be an expensive call.  We only
that was my thought where it might not end up only being used internally. but I'm good with this. Good job. tested locally :+1:  LGTM

2023-09-11 21:46 UTC, PThorpe92 submitted a review, later dismissed

2023-09-11 22:55 UTC, PThorpe92 commented
Any day now these macos tests will run -_-

It looks like they are finished but just haven't reported their status yet? wtf

2023-09-12 05:58 UTC, cafkafk requested changes
Sorry to bring bad news, but this had an error for me :E 
 
![Uploading 2023-09-12_07-56.png…]()

2023-09-12 06:04 UTC, cfxegbert commented
> cargo run --release -q -- --blocksize -l --hyperlink --grid --git-repos -x --time-style relative  --git --header --icons -Z -@ -o ~/.config

Different use of canonicalize.  I will search the whole code base for calls to canonicalize.

2023-09-12 06:42 UTC, cafkafk reviewed
That does fix my error :+1:

2023-09-13 01:16 UTC, PThorpe92 commented
I want to merge this ASAP.

@daviessm any chance you have an opportunity to test this fork out on a windows machine?

2023-09-13 10:43 UTC, daviessm commented
> @daviessm any chance you have an opportunity to test this fork out on a windows machine?

Sure, I haven't been following much - what exactly needs testing? I should have some time late evening UK time today to look at this.

2023-09-13 11:23 UTC, cafkafk commented
> > @daviessm any chance you have an opportunity to test this fork out on a windows machine?
> 
> Sure, I haven't been following much - what exactly needs testing? I should have some time late evening UK time today to look at this.

Essentially running `eza -l` on broken symlinks, and just general testing, #255 shows the bug this fixes for context. Although @cfxegbert might have a better idea what would specifically be good to cover this.

2023-09-13 11:40 UTC, PThorpe92 commented
I would say run 
    
    eza -l@xh
on a dir with a symlink to a file on an unmounted thumb or hard drive
and then run 
    
    eza --blocksize -l --hyperlink --grid --git-repos -x --time-style relative --git --header --icons -Z -@ -o 

on the same location

just because those are the two commands that seem to cover all the bases we used previously :+1:

2023-09-13 11:52 UTC, daviessm commented
When you say symlink on Windows, does that mean a shortcut?

2023-09-13 11:53 UTC, PThorpe92 commented
Lol good point... umm yeah i think thats the best they got right?

2023-09-13 12:12 UTC, ChrisDenton commented
On windows powershell do:

```
ni -i sym link_name -v target_name
```

Or more verbosely:

```
New-Item -ItemType SymbolicLink -Path "link_name" -Target "target_name"
```

2023-09-13 16:48 UTC, daviessm commented
> `New-Item -ItemType SymbolicLink -Path "link_name" -Target "target_name"`

Then
> ```eza -l@xh```

And
> ```eza --blocksize -l --hyperlink --grid --git-repos -x --time-style relative --git --header --icons -Z -@ -o ```

Gave errors with v0.11.1, work as expected with this branch on Windows. LGTM.

2023-09-13 17:16 UTC, PThorpe92 approved these changes

2023-09-13 17:17 UTC, PThorpe92 approved these changes

2023-09-13 17:27 UTC, merged