feat: Support --mount option on Mac
eza-community/eza pull request #291
Opened 2023-09-13 00:44 UTC by cfxegbert

New integration tests do not run correctly on OS X Ventura so could not complete testing.  We need to fix the integration tests in another ticket.  See https://matrix.to/#/!oTWUEgcTDkFeeuGXEo:gitter.im/$sHUfOebw04q5cobvWx8T5jodBeBfAnv4CihS4cn5K_I?via=gitter.im&via=matrix.org&via=nixos.dev

2023-09-13 20:11 UTC, daviessm commented
Nice one! I don't suppose there's a crate we could use to get the mounts so we don't have to worry so much about `unsafe` is there?

2023-09-13 20:16 UTC, daviessm requested changes
Just a few comments on documentation of `unsafe` blocks. The change seems logical overall.

2023-09-13 20:16 UTC, daviessm commented on src/fs/mounts/macos.rs
> +    let mut count: i32 = unsafe { getfsstat(ptr::null_mut(), 0, MNT_NOWAIT) };
If the `unsafe` is unavoidable please can you add SAFETY comments as per https://rust-lang.github.io/rust-clippy/master/#/undocumented_unsafe_blocks?

2023-09-13 20:16 UTC, daviessm commented on src/fs/mounts/macos.rs
> +        mntbuf.resize_with(count as usize, || unsafe { mem::zeroed() });
Same - please document `unsafe` block

2023-09-13 20:16 UTC, daviessm commented on src/fs/mounts/macos.rs
> +        count = unsafe { getfsstat(mntbuf.as_mut_ptr(), bufsize as c_int, MNT_NOWAIT) };
Same - please document `unsafe` block

2023-09-13 20:16 UTC, daviessm commented on src/fs/mounts/macos.rs
> +        return Err(Error::GetFSStatError(unsafe { *__error() }));
Same - please document `unsafe` block

2023-09-13 20:16 UTC, daviessm commented on src/fs/mounts/macos.rs
> +            unsafe { CStr::from_ptr(mnt.f_mntonname.as_ptr().cast::<c_char>()) }.to_bytes()
Same - please document `unsafe` block

2023-09-13 20:16 UTC, daviessm commented on src/fs/mounts/macos.rs
> +        let fstype = unsafe { CStr::from_ptr(mnt.f_fstypename.as_ptr().cast::<c_char>()) }
Same - please document `unsafe` block

2023-09-13 20:16 UTC, daviessm commented on src/fs/mounts/macos.rs
> +        let source = unsafe { CStr::from_ptr(mnt.f_mntfromname.as_ptr().cast::<c_char>()) }
Same - please document `unsafe` block

2023-09-16 05:37 UTC, cafkafk approved these changes
Nice, thanks for refactoring the mess I made of `lib.rs`. Cool to see we get to leverage `1.70` already with `OnceLock`. Hopefully we get clap merged very soon so the comment can be addressed.

2023-09-16 05:37 UTC, merged