feat: add quotations around filenames with spaces. exa pr#1165
eza-community/eza pull request #318
Opened 2023-09-14 14:08 UTC by PThorpe92

https://github.com/eza-community/eza/issues/311

the commit history was a mess on the original PR, and its time to revisit this :D 

![image](https://github.com/eza-community/eza/assets/121899304/f6434620-2eda-4d77-996a-63f038f7260c)
 
feedback/testers needed

2023-09-15 05:37 UTC, cafkafk commented
Wait, are we doing this before #195, not sure if we came to any conclusions on element.

2023-09-16 01:19 UTC, PThorpe92 commented
> Wait, are we doing this before #195, not sure if we came to any conclusions on element.

This came about from the referenced issue + digging up a couple of the remaining exa PR's.. I don't remember this one being the one we were waiting on clap for, but that is perfectly fine with me either way as I think it's a good 1.0 addition.

2023-09-16 15:13 UTC, gierens commented
Just tested this locally, looks solid ... but I agree we should wait for clap and the properly review this.

2023-09-16 22:36 UTC, ariasuni commented
I think quotes should use a different color when they’re not part of the filename but added by exa, so that we can see immediately that they’re not part of the filename

2023-09-17 05:40 UTC, gierens commented
> I think quotes should use a different color when they’re not part of the filename but added by exa, so that we can see immediately that they’re not part of the filename

Uh that's ah really nice idea :o :)

2023-09-19 18:47 UTC, cafkafk commented
Maybe we shouldn't block this until clap is done, given how big of a task that turned out to be?

2023-09-21 09:46 UTC, gierens commented on src/options/help.rs
> +
why the extra blank line?

2023-09-21 09:47 UTC, gierens commented on src/options/flags.rs
> +
Don't need the extra blank line here.

2023-09-21 09:47 UTC, gierens commented on src/options/flags.rs
> +
Here too, no extra blank line needed.

2023-09-21 09:52 UTC, gierens commented on src/output/file_name.rs
> +
Too many blanks

2023-09-21 09:53 UTC, gierens commented on src/options/help.rs
> +
too many blanks

2023-09-21 09:54 UTC, gierens commented on src/options/file_name.rs
> +
too many blanks

2023-09-21 09:54 UTC, gierens commented on src/options/file_name.rs
> +
too many blanks

2023-09-21 09:55 UTC, gierens requested changes
LGTM :) ... just marked a few formatting nitpicks :D

2023-09-21 14:04 UTC, PThorpe92 commented
@gierens  those lines were all left over from stripping the other functionality from the PR and fixing merge conflicts, just to give some context. fixing now :D

2023-09-22 04:05 UTC, sevz17 commented
> I think quotes should use a different color when they’re not part of the filename but added by exa, so that we can see immediately that they’re not part of the filename
> 

That's a good idea, but what happens when you use `--color=never`?

2023-09-22 13:08 UTC, gierens commented
> @gierens those lines were all left over from stripping the other functionality from the PR and fixing merge conflicts, just to give some context. fixing now :D

Yeah makes total sense ... I mean without rustfmt such things are bound to happen ... that's why I made the PR for that. :D

2023-09-22 21:07 UTC, ariasuni commented
> > I think quotes should use a different color when they’re not part of the filename but added by exa, so that we can see immediately that they’re not part of the filename
> 
> That's a good idea, but what happens when you use `--color=never`?

`ls` align files differently, I think it’s a great idea but not sure how easy it is to do it in our current code base.

```
$ ls -l
total 52
drwxr-xr-x 15 ariasuni ariasuni  4096  6 sept. 16:10  administratif/
drwxr-xr-x  9 ariasuni ariasuni  4096 17 sept. 01:09  documents/
drwxr-xr-x 12 ariasuni ariasuni  4096  6 juil. 13:33  images/
drwxr-xr-x 21 ariasuni ariasuni  4096 28 août  01:33  jeux/
drwxr-xr-x  6 ariasuni ariasuni  4096 22 sept. 18:58  musique/
drwxr-xr-x 11 ariasuni ariasuni  4096 17 juil.  2021  projets/
drwxr-xr-x  5 ariasuni ariasuni  4096 22 sept. 20:14  téléchargements/
-rw-r--r--  1 ariasuni ariasuni     0 22 sept. 23:06 'test file'
drwxr-xr-x  6 ariasuni ariasuni 20480 22 sept. 20:14  vidéos/
```

2023-09-23 04:06 UTC, cafkafk approved these changes
Sandboxed integration tests pass, and this looks good to me when locally testing.

![2023-09-23_06-03](https://github.com/eza-community/eza/assets/89321978/3223d833-aa76-4cde-bcc8-9a44ce28b56d)
The `--no-quotes` flag also works
![2023-09-23_06-03_1](https://github.com/eza-community/eza/assets/89321978/ddaa3a0c-003d-4a59-bf13-20d7b05533f3)

Fish and zsh completions also work, and the man pages are also correct. Nice change, LGTM :+1:

2023-09-23 04:07 UTC, cafkafk commented
> I think it’s a great idea but not sure how easy it is to do it in our current code base.

Could we do a hacky `\r` prefixed to the first quote? I'm not entirely sure how the rendering code works, or if we wanna actually change the grid code to do this.

2023-09-23 18:10 UTC, gierens approved these changes

2023-09-24 17:51 UTC, PThorpe92 commented
Had to fix merge conflicts with main.. idk why tests didn't pass. seems to still work fine locally. I'll look at this deeper

2023-09-26 08:06 UTC, MartinFillon commented
For the unit tests action your code is not formatted and as for nix the code doesn't follow nix flake check guidelines.

2023-09-27 01:03 UTC, cafkafk approved these changes
Just checked out the changes, still seem good to me.

2023-09-27 01:26 UTC, merged

2023-10-11 04:41 UTC, eggbean commented
I know `ls` does this, but what is the practical reason for it? It just looks messier to me.

2023-10-11 08:46 UTC, gierens commented
> I know `ls` does this, but what is the practical reason for it? It just looks messier to me.

There are several cases where this can help ... to actually see trailing spaces, to directly copy paste those filenames into further commands without having to add the quotes manually, and of course also for piping eza output into other things ...

If you don't want to see the quotes to can use the `--no-quotes` option.

2023-10-20 10:34 UTC, aarondill commented
This pr breaks grid layout when files with spaces are included! Though seemly only when grid and icons are included...
Here is a repro for this bug: https://gist.github.com/aarondill/bf4d306a1819f1c3acb81d5b2a8f7629
Notice the alignment of the first row (the one with the spaces) is messed up when using quotes and icons:

```shell
 > echo Broken with quotes and icons
Broken with quotes and icons
> eza --grid --icons -- /tmp/tmp.Hc5SgTEG8i
 'a file with spaces'   long-file-name-5   long-file-name-10   long-file-name-15   long-file-name-20   long-file-name-25   long-file-name-30   long-file-name-35   long-file-name-40
 long-file-name-1     long-file-name-6   long-file-name-11   long-file-name-16   long-file-name-21   long-file-name-26   long-file-name-31   long-file-name-36
 long-file-name-2     long-file-name-7   long-file-name-12   long-file-name-17   long-file-name-22   long-file-name-27   long-file-name-32   long-file-name-37
 long-file-name-3     long-file-name-8   long-file-name-13   long-file-name-18   long-file-name-23   long-file-name-28   long-file-name-33   long-file-name-38
 long-file-name-4     long-file-name-9   long-file-name-14   long-file-name-19   long-file-name-24   long-file-name-29   long-file-name-34   long-file-name-39
> echo It works without quotes
It works without quotes
> eza --grid --icons --no-quotes -- /tmp/tmp.Hc5SgTEG8i
 a file with spaces   long-file-name-5   long-file-name-10   long-file-name-15   long-file-name-20   long-file-name-25   long-file-name-30   long-file-name-35   long-file-name-40
 long-file-name-1     long-file-name-6   long-file-name-11   long-file-name-16   long-file-name-21   long-file-name-26   long-file-name-31   long-file-name-36
 long-file-name-2     long-file-name-7   long-file-name-12   long-file-name-17   long-file-name-22   long-file-name-27   long-file-name-32   long-file-name-37
 long-file-name-3     long-file-name-8   long-file-name-13   long-file-name-18   long-file-name-23   long-file-name-28   long-file-name-33   long-file-name-38
 long-file-name-4     long-file-name-9   long-file-name-14   long-file-name-19   long-file-name-24   long-file-name-29   long-file-name-34   long-file-name-39
> echo It seems to work without icons tho...
It seems to work without icons tho...
> eza --grid -- /tmp/tmp.Hc5SgTEG8i
'a file with spaces'  long-file-name-5  long-file-name-10  long-file-name-15  long-file-name-20  long-file-name-25  long-file-name-30  long-file-name-35  long-file-name-40
long-file-name-1      long-file-name-6  long-file-name-11  long-file-name-16  long-file-name-21  long-file-name-26  long-file-name-31  long-file-name-36
long-file-name-2      long-file-name-7  long-file-name-12  long-file-name-17  long-file-name-22  long-file-name-27  long-file-name-32  long-file-name-37
long-file-name-3      long-file-name-8  long-file-name-13  long-file-name-18  long-file-name-23  long-file-name-28  long-file-name-33  long-file-name-38
long-file-name-4      long-file-name-9  long-file-name-14  long-file-name-19  long-file-name-24  long-file-name-29  long-file-name-34  long-file-name-39
```

2023-10-20 10:35 UTC, aarondill commented
Sorry for the ping. I didn't see #515 or #547.

2023-12-04 20:01 UTC, DenebTM commented
oh cool, my PR finally did get merged, without credit but alas :3

> I know `ls` does this, but what is the practical reason for it? It just looks messier to me.

My motivation was: KDE's Konsole relies on the quotes for shell integration stuff, like hovering, CTRL+clicking, or highlighting file names by double click.

2023-12-05 00:17 UTC, PThorpe92 commented
>oh cool, my PR finally did get merged, without credit but alas :3

Yeah looks like that is my fault, I think the original PR cafk moved over from exa had ping'd you as the author, but that ended up sitting around forever on an old branch so I had to fix so many conflicts and whatnot that I put in a new PR, and only put the link ( `exa PR#1165` ) in the name. 

My apologies, and thank you for the contribution :heart:

2023-12-14 01:45 UTC, John-Gee commented
I think the different color for eza quotes from @ariasuni  is a great idea, cause as it is it's hard to see at a glance.

Also is it possible to have the same type of quotes for all? For instance if a folder uses single quotes in its filename eza will add double quote for that folder but will still use single quotes for the rest, it's kind of messy.

Quotes also break alignment I'd say, is it possible to add a spacing to those that don't need quotes, or maybe someone has a better idea for that? Adding quotes to all? Not sure.

2023-12-15 06:48 UTC, cafkafk commented
@John-Gee It would probably be a good idea to open an issue or discussion for this, that way your feedback wont be lost!

2023-12-15 09:39 UTC, John-Gee commented
@cafkafk very well, done with #728 thank you!