Add new icons and new folder icon
eza-community/eza pull request #395
Opened 2023-09-19 11:44 UTC by Brijeshkrishna

Updated folder icon with rounded corners and new icons

2023-09-19 14:06 UTC, Brijeshkrishna commented
feat: Added new icons, changed folder icons with rounded corners.

![Screenshot_20230919_192001-1](https://github.com/eza-community/eza/assets/63464137/1b4feca1-a804-41c1-8eab-f899278ff96b)

2023-09-19 14:55 UTC, cafkafk requested changes
We've discussed the folder icon in the past https://github.com/eza-community/eza/pull/137. I suggest you split this up into multiple PRs, one for the folder icon change, which is bound to require a bit of discussion, and one for the other icons, which should be much quicker.

2023-09-19 15:58 UTC, Brijeshkrishna commented
Reverted

2023-09-19 16:07 UTC, cafkafk requested changes
I tried to rebase your commits locally to change the summaries so the test pass, but I don't have permission to do that. You'll have to change them, and they should be squashed into a single commit

2023-09-19 17:13 UTC, cfxegbert reviewed
Sorry about being a bit nit picky here.  Some of these comments about which icon we should use I need to address and will get back to you.

2023-09-19 17:27 UTC, cfxegbert commented on src/output/icons.rs
> +    "fdmdownload"    => '\u{f0965}',             // 󰥥
Can we change this to use the same icon as "download".  The simpler icon reads better at small sizes.

2023-09-19 17:45 UTC, Brijeshkrishna commented on src/output/icons.rs
> +    const LANG_RUST: char       = '\u{e68b}';  // 
e68b is bigger than e7a8 , e68b is normal size compare to other icons

2023-09-19 17:54 UTC, cfxegbert commented on src/output/icons.rs
> +    const LANG_RUST: char       = '\u{e68b}';  // 
Good catch.  Can you update all the icon comments for LANG_RUST in the file?

2023-09-20 09:44 UTC, Brijeshkrishna commented on src/output/icons.rs
> +    "bash"           => '\u{ebca}',              // 
since bash icon is available.

2023-09-20 17:56 UTC, cfxegbert commented on src/output/icons.rs
> +    "bash"           => '\u{ebca}',              // 
We would rather stay consistent with the other shell icons.

2023-09-21 16:12 UTC, devinherron commented on src/output/icons.rs
> +    "Favorite"            => '\u{f069d}',           // 󰚝
Windows 10 and 11 have "Contacts" and "Favorites" (plural)

2023-09-21 17:39 UTC, Brijeshkrishna commented on src/output/icons.rs
> +    "Favorite"            => '\u{f069d}',           // 󰚝
Yes, and if the user created this folder on Linux, let it support it.

2023-09-21 17:42 UTC, Brijeshkrishna commented on src/output/icons.rs
> +    "Drive"               => '\u{f024e}',           // 󰉎
No, changed to 🖴 U+1F5B4

2023-09-21 18:10 UTC, PThorpe92 commented on src/output/icons.rs
> +    "Favorite"            => '\u{f069d}',           // 󰚝
I agree 'Favorites' needs to be plural

2023-09-24 06:01 UTC, cfxegbert commented on src/output/icons.rs
> +    "Drive"               => '\u{f024e}',           // 󰉎
1f5b4 is not a codepoint in Nerdfonts

2023-09-24 10:43 UTC, Brijeshkrishna commented on src/output/icons.rs
> +    "Drive"               => '\u{f024e}',           // 󰉎
Yes, it is not a nerd font, but it is supported by all fonts (it is in the Unicode Miscellaneous Symbols and Pictographs block).

2023-09-24 21:35 UTC, cfxegbert commented on src/output/icons.rs
> +    "Drive"               => '\u{f024e}',           // 󰉎
It is not supported by any of the NerdFonts I have tested.

2023-09-25 00:03 UTC, cfxegbert commented on src/output/icons.rs
> +    "Drive"               => '\u{f024e}',           // 󰉎
Code I used to test on my mac

```python
from pathlib import Path
from fontTools.ttLib import TTFont
import unicodedata

def find_fonts():
    for font_dir in ["/System/Library/Fonts", "/Library/Fonts", "~/Library/Fonts"]:
        for path in Path(font_dir).expanduser().rglob("*.ttf"):
            yield str(path)


def char_in_font(unicode_char, font):
    for cmap in font['cmap'].tables:
        if cmap.isUnicode():
            if ord(unicode_char) in cmap.cmap:
                return True
    return False

def test_char(char):
    for fontpath in find_fonts():
        font = TTFont(fontpath)
        if char_in_font(char, font):
            # name = unicodedata.name(char)
            # print(f"{char} {name} in {fontpath}")
            print(f"{char} in {fontpath}")

#test_char("\U000f024e")
test_char("\U0001f5b4")
```

2023-09-25 00:26 UTC, cfxegbert commented on src/output/icons.rs
> +    "Drive"               => '\u{f024e}',           // 󰉎
Looking at the table https://en.wikipedia.org/wiki/Miscellaneous_Symbols_and_Pictographs there are large gaps at the end of the table starting at U+1F54x

2023-09-26 07:56 UTC, MartinFillon commented on src/output/icons.rs
I am also going to be picky but do we think about giving all icons a constant in the Icons enum ?

2023-09-27 13:41 UTC, Brijeshkrishna commented on src/output/icons.rs
> +    "Drive"               => '\u{f024e}',           // 󰉎
Ok then, removed.

2023-09-29 05:10 UTC, cfxegbert commented on src/output/icons.rs
I'll do that in a different pull request.

2023-09-29 05:17 UTC, cfxegbert approved these changes

2023-09-29 05:55 UTC, cafkafk commented
I'll take a look

2023-09-29 06:03 UTC, cafkafk requested changes
You'll have to rebase and fix the commit summaries, so they conform to conventional commits. Else, testing this locally looks good. Nice work!

2023-09-29 23:30 UTC, cfxegbert commented on src/output/icons.rs
> +    "README"              => Icons::README,         // 󰂺
Just noticed this is not sorted properly.  You can fix or I can fix the next time I edit the icons.

2023-09-29 23:47 UTC, cfxegbert commented
# Added extensions
| Ext           | Icon |     Class      |  Code   | Notes |
|---------------|:----:|:--------------:|:-------:|-------|
| `bdf`         |     |   nf-fa-font   | \uf031  |       |
| `fdmdownload` |  󰇚  | nf-md-download | \uf01da |       |
| `lib`         |     | nf-cod-library | \ueb9c  |       |
| `psf`         |     |   nf-fa-font   | \uf031  |       |
| `readme`      |  󰂺  |   nf-md-book   | \uf00ba |       |

# Changed extensions
| Ext     | Icon |     Class      |  Code  | Old icon |    Old class     | Old code | Notes                                                    |
|---------|:----:|:--------------:|:------:|:--------:|:----------------:|:--------:|----------------------------------------------------------|
| `dll`   |     | nf-cod-library | \ueb9c |         |  nf-fa-windows   |  \uf17a  |                                                          |
| `r`     |     |   nf-seti-r    | \ue68a |         | nf-fa-registered |  \uf25d  | Change from generic registered symbol to R language icon |
| `rdata` |     |   nf-seti-r    | \ue68a |         | nf-fa-registered |  \uf25d  | Change from generic registered symbol to R language icon |
| `rds`   |     |   nf-seti-r    | \ue68a |         | nf-fa-registered |  \uf25d  | Change from generic registered symbol to R language icon |
| `rlib`  |     |  nf-seti-rust  | \ue68b |         |   nf-dev-rust    |  \ue7a8  | Same icon with bigger size                               |
| `rmeta` |     |  nf-seti-rust  | \ue68b |         |   nf-dev-rust    |  \ue7a8  | Same icon with bigger size                               |
| `rs`    |     |  nf-seti-rust  | \ue68b |         |   nf-dev-rust    |  \ue7a8  | Same icon with bigger size                               |

# Removed extensions
| Ext | Notes |
|-----|-------|

# Added files
| Name        | Icon |        Class         |  Code   | Notes                          |
|-------------|:----:|:--------------------:|:-------:|--------------------------------|
| `Contacts`  |  󰉌  | nf-md-folder_account | \uf024c | Contacts directory on Windows  |
| `Favorites` |  󰚝  |  nf-md-folder_star   | \uf069d | Favorites directory on Windows |
| `home`      |  󱂵  |  nf-md-folder_home   | \uf10b5 | Home directory                 |
| `README`    |  󰂺  |      nf-md-book      | \uf00ba |                                |

# Changed files
| Name            | Icon |    Class     |  Code  | Old icon |  Old class  | Old code | Notes                      |
|-----------------|:----:|:------------:|:------:|:--------:|:-----------:|:--------:|----------------------------|
| `.rustfmt.toml` |     | nf-seti-rust | \ue68b |         | nf-dev-rust |  \ue7a8  | Same icon with bigger size |
| `Cargo.lock`    |     | nf-seti-rust | \ue68b |         | nf-dev-rust |  \ue7a8  | Same icon with bigger size |
| `Cargo.toml`    |     | nf-seti-rust | \ue68b |         | nf-dev-rust |  \ue7a8  | Same icon with bigger size |
| `release.toml`  |     | nf-seti-rust | \ue68b |         | nf-dev-rust |  \ue7a8  | Same icon with bigger size |

# Removed files
| Name | Notes |
|------|-------|

2023-09-30 08:30 UTC, cafkafk requested changes
Seems like you have a formatting issue:

```
treefmt-check> [INFO]: #rustfmt: 61 files processed in 1.27s
treefmt-check> traversed 201 files
treefmt-check> matched 104 files to formatters
treefmt-check> left with 104 files after cache
treefmt-check> of whom 1 files were re-formatted
treefmt-check> all of this in 1s
treefmt-check> On branch main
treefmt-check> Changes not staged for commit:
treefmt-check>   (use "git add <file>..." to update what will be committed)
treefmt-check>   (use "git restore <file>..." to discard changes in working directory)
treefmt-check>  modified:   src/output/icons.rs
treefmt-check> no changes added to commit (use "git add" and/or "git commit -a")
treefmt-check> diff --git a/src/output/icons.rs b/src/output/icons.rs
treefmt-check> index 7242ea4..c13a3c8 100644
treefmt-check> --- a/src/output/icons.rs
treefmt-check> +++ b/src/output/icons.rs
treefmt-check> @@ -131,7 +131,7 @@ const DIRECTORY_ICONS: Map<&'static str, char> = phf_map! {
treefmt-check>      "etc"                 => Icons::FOLDER_CONFIG,  // 
treefmt-check>      "Favorites"           => '\u{f069d}',           // 󰚝
treefmt-check>      "hidden"              => Icons::FOLDER_HIDDEN,  // 󱞞
treefmt-check> -    "home"                => '\u{f10b5}',           // 󱂵 
treefmt-check> +    "home"                => '\u{f10b5}',           // 󱂵
treefmt-check>      "include"             => Icons::FOLDER_CONFIG,  // 
treefmt-check>      "Mail"                => '\u{f01f0}',           // 󰇰
treefmt-check>      "Movies"              => '\u{f0fce}',           // 󰿎
treefmt-check> @@ -145,7 +145,7 @@ const DIRECTORY_ICONS: Map<&'static str, char> = phf_map! {
treefmt-check>      "Videos"              => '\u{f03d}',            // 
treefmt-check>      "xbps.d"              => Icons::FOLDER_CONFIG,  // 
treefmt-check>      "xorg.conf.d"         => Icons::FOLDER_CONFIG,  // 
treefmt-check> -    
treefmt-check> +
treefmt-check>  };
treefmt-check>  
treefmt-check>  /// Mapping from full filenames to file icon. This mapping should also contain
```

2023-09-30 16:39 UTC, cafkafk approved these changes
And that's it. Integration tests pass, CI passes, everything seems to work. Thanks for your contribution @Brijeshkrishna, LGTM :heart:

2023-09-30 16:40 UTC, merged