fix(git-repos): don’t show color when color is disabled
eza-community/eza pull request #402
Opened 2023-09-21 00:36 UTC by ariasuni

Fix #391

In the end, I find that the way traits are used for this is pretty elegant.

A `trait` is used to define a set of functions, each returning a `Style` for a particular element or type of element. This trait is implemented on `Theme`, and when we pass around the actual theme, we cast it to a particular `trait` in a particular render function, which means we can only use the `Style`s returned by the functions of the trait.

Also I changed the colors to use the terminal theme, and now the status column don’t even appear if we use `--git-repos-no-status`.

Result:
![image](https://github.com/eza-community/eza/assets/2446451/5ba4aa86-a387-47ea-898e-8030f867995f)
![image](https://github.com/eza-community/eza/assets/2446451/0b5108d6-c0d5-4a22-b5f6-099936baa5ea)

2023-09-21 03:23 UTC, cafkafk requested changes
This looks very nice! This isn't a full review, but this broke the `long_git_repos_no_status_nix.toml` tests. That's expected when we change it's behavior thou, so I'll make it reflect this PR.
![2023-09-21_05-20](https://github.com/eza-community/eza/assets/89321978/17b2a10f-76db-4b5a-b966-ce43be0f39a0)

2023-09-21 17:15 UTC, PThorpe92 commented
Discussed on Element. LGTM :heart:

2023-09-21 17:58 UTC, PThorpe92 approved these changes

2023-09-23 03:56 UTC, cafkafk approved these changes
So I found time to test this fully. `NO_COLOR=1` works, all the behavior works as expected, without breaking anything, and sandboxed integration tests pass. LGTM, thanks for fixing this! :+1:

2023-09-23 04:08 UTC, merged