build: add `codegen-units = 1` and remove `opt-level = 3`
eza-community/eza pull request #491
Opened 2023-10-06 21:03 UTC by acuteenvy

`opt-level = 3` is the default for release builds (https://doc.rust-lang.org/stable/book/ch14-01-release-profiles.html).
`codegen-units = 1` lengthens the build by about 4 seconds on my system and produces a ~20KiB smaller binary.

2023-10-07 00:23 UTC, ariasuni submitted a review, later dismissed

2023-10-07 03:20 UTC, cafkafk requested changes

2023-10-07 03:20 UTC, cafkafk commented on Cargo.toml
> -opt-level = 3
Even if it's the default I don't see the value in not being explicit about it. This line should be kept.

2023-10-07 03:30 UTC, cafkafk commented
> lengthens the build by about 4 seconds

for me it was 32 seconds without and 44.9 seconds with

2023-10-07 03:35 UTC, cafkafk commented
> a ~20KiB smaller binary.

For me, without is 1654056 with is 1637672, which is about 1% smaller

2023-10-08 03:47 UTC, cafkafk approved these changes
lgtm

2023-10-08 03:47 UTC, merged