feat: add option --smart-group
eza-community/eza pull request #514
Opened 2023-10-11 12:54 UTC by liketurbo

Relevant issue: #480

2023-10-12 03:49 UTC, cafkafk requested changes
You'll need to add this to zsh, fish, and bash completions, as well as the man page.

2023-10-13 12:35 UTC, liketurbo commented
> You'll need to add this to zsh, fish, and bash completions, as well as the man page.

I probably didn't do bash completions correctly, as there isn't much to use as a template ... so I'd gladly accept any help with that one 😊

2023-10-14 17:47 UTC, cafkafk requested changes

2023-10-14 17:47 UTC, cafkafk commented on completions/bash/eza
> +        --help|-v|--version|--smart-group)
(Just reminding myself to check this before merging)

2023-10-15 05:45 UTC, cafkafk approved these changes
Manpage generation works, integration tests work, and the expected behavior is present without breaking other functionality (as far as I can tell).

2023-10-15 05:45 UTC, merged