feat: add `--decay` option to highlight newer files
eza-community/eza pull request #526
Opened 2023-10-12 18:30 UTC by aashirbadb

This PR adds `--decay` option that highlights newer files. It has two modes:
-   `absolute`: Evaluates based on file modification time relative to the past year.
-   `relative`: Considers file modification time in relation to other files.

Both modes use a luminance formula `min + (1.0 - min) * exp(-4.0 * (1.0 - x))`, where `min` can be customized by using the 'EZA_MIN_LUMINANCE' environment variable.

Screenshots:
- relative mode
![image](https://github.com/eza-community/eza/assets/89701256/a85b3f5f-4705-45be-be68-3db5bf9a9aa9)
- absolute mode
![image](https://github.com/eza-community/eza/assets/89701256/362151b6-4e2a-42dd-a731-8996d75e8a5a)
- tree
![image](https://github.com/eza-community/eza/assets/89701256/decd71b9-c615-45b1-bd11-17e26940f4d6)

(I'm calling it `decay` because I couldn't think of a better name 😅. I'd greatly appreciate any suggestions for a more fitting name)

Resolves #486

2023-10-13 02:06 UTC, PThorpe92 commented
I like the term decay.. it's a hell of a lot better than `rot` lmao

2023-10-13 04:53 UTC, cafkafk requested changes
This is looking cool.

For conventional commits: `doc: add --decay option and EZA_MIN_LUMINANCE env var` needs to be `docs: add --decay option and EZA_MIN_LUMINANCE env var`

2023-10-13 09:03 UTC, cafkafk requested changes
Could we have default behavior where `--decay` without any arguments default to `--decay relative`?

2023-10-13 13:49 UTC, aashirbadb commented
> Could we have default behavior where `--decay` without any arguments default to `--decay relative`?

I tried adding it but it looks like `TakesValue::Optional` doesn't work like it should.
Passing `--decay something` gives `(decay, Some(something))` instead of `(decay, Some(default_value))`(if something is invalid option for the flag) or `(decay, Some(something))` (if something is valid option).

https://github.com/eza-community/eza/blob/9805dd587936ba9e8e61d216b5f96b51b4676a24/src/options/parser.rs#L201-L207

Should I fix this(maybe in a separate PR?) or wait for  #197 and implement it then?

2023-10-13 16:30 UTC, PThorpe92 commented
>Should I fix this(maybe in a separate PR?) or wait for https://github.com/eza-community/eza/pull/197 and implement it then?

I am currently working through another implementation that gives a flag a default value. Once I'm finished I'll take a look and see if we can get it figured out.

Hopefully clap will be very soon. Honestly, this is a really exciting change and part of me does want to wait and release the functionality with `v1.0`

Feel free to come to the matrix channel too if you want to talk about it

2023-10-23 17:42 UTC, cohml commented
> Feel free to come to the matrix channel too if you want to talk about it

Link to said channel please? I'm not familiar with this "matrix", but would like to be a fly on the wall. Thanks.

2023-10-23 21:52 UTC, PThorpe92 commented
If you go to the main page the "Chat on gitter" button

https://matrix.to/#/#eza-community:gitter.im is the link

2023-10-26 11:57 UTC, Delapouite commented
Also, should the option `--color-scale` be renamed to avoid any confusion about where it applies ? `size` vs `date`?

2023-10-26 13:05 UTC, PThorpe92 commented
also, I was able to get the `--icons` flag to take a default value and have a `TakesValue::Optional(Some(VALUE))`

So if you want to have this take an optional argument and set a default value, you can look at how icons does it now.

2023-10-26 13:17 UTC, Delapouite commented
You're right PThorpe92, the notion of `color-scale` could even reach further.

Non exhaustive list of possible columns :

- date: old → new (this PR)
- size: small → big (kind of current behavior of `--color-scale`, but limited to magnitude kilo, mega, tera…)
- links count : few → lot
- octal permissions : very-restricted → open bar (777)
- …

2023-10-26 13:30 UTC, PThorpe92 commented
I think the way to go would be to have breaking changes, and make sure that --color-scale has a value. It will break people's alias's, but it will also alert them to the new feature.

Have you tested this alongside the current --color-scale flag? How does that work?

2023-10-26 13:43 UTC, aashirbadb commented
> That is a good question.. how would you feel about making this a value for the color-scale flag? e.g. `--color-scale=age` || `--color-scale=size`

`--decay` takes two values so I can just change it so that `relative` is default value when `--color-scale=age` is used and it can be changed to absolute mode using `--color-scale=age --decay=absolute`.

> I think the way to go would be to have breaking changes, and make sure that --color-scale has a value. It will break people's alias's, but it will also alert them to the new feature.

We can also allow multiple choices using comma separated list(`--color-scale=age,size`) and maybe add an `all` choice which could be optional flag to not introduce a breaking change?

2023-10-26 13:54 UTC, PThorpe92 commented
My thought process was kinda specifically to introduce the feature. Adding a value to a flag isn't nearly as exciting as the new `decay` option. But I do like that idea. It could just default to `all`

2023-10-27 08:28 UTC, aashirbadb commented
I think it would be better to remove the `--decay` flag and use  `--color-scale` and add a new flag(something like `--color-scale-mode`) to select the mode(`fixed`,`gradient`). 

Fixed would work like the current `--color-scale` and gradient would work like relative mode. 

This would also make it easier to add more columns like Delapouite suggested.

2023-10-28 11:30 UTC, aashirbadb commented
I added this to size and it looks pretty cool.

![image](https://github.com/eza-community/eza/assets/89701256/58a4c226-0871-43cf-b07f-d62a3757890e)

2023-11-01 05:33 UTC, cafkafk requested changes
Looks like you have a formatting issue, if you're using nix, this is easily fixed with `nix fmt`.

Also, your breaking change should have a `BREAKING` footer (or w/e exactly it's called) as specified by conventional commits, you can find more info about it in the conventional commits spec.

2023-11-08 17:34 UTC, MartinFillon requested changes

2023-11-08 17:34 UTC, MartinFillon commented on README.md
> +- **--colo[u]r-scale=(field)**: highlight levels of `field` distinctly(all, age, size)
I don't like age as `Field name` could you use the name used on the `--header` option

2023-11-08 17:34 UTC, MartinFillon commented on src/options/theme.rs
> +    // test!(scale_8:  ColourScale <- [                                 ];   Complain => Ok(ColourScale::Fixed));
Please remove those comments and test the code

2023-11-08 17:34 UTC, MartinFillon commented on src/options/theme.rs
> +    // test!(scale_8:  ColourScale <- [                                 ];   Complain => Ok(ColourScale::Fixed));
If not possible to test just remove it

2023-11-08 17:34 UTC, MartinFillon commented on src/output/decay.rs
> +) {
Why is this function not in the impl above ?

2023-11-08 17:34 UTC, MartinFillon commented on src/output/render/size.rs
> +                    NumberPrefix::Prefixed(p, _) => Some(p),
please format those lines

2023-11-08 18:46 UTC, closed without merging