fix(symlink): don’t display target’s size if we’re not dereferencing
eza-community/eza pull request #539
Opened 2023-10-17 16:15 UTC by ariasuni

I also took the liberty of changing the code to display nothing (`-`) instead of the size of the link itself. Symlinks are very similar to directories in the sense they their own size isn’t very informative, that’s why we were already ignoring the directories size.

For reviewers:
The first bloc of code shouldn’t have been in the first place, I believe it to be a merge mistake.

Fix #112
Fix #530

2023-10-18 05:29 UTC, cafkafk requested changes
This seems to be working, could you also implement this behavior for the `--blocksize` flag?

2023-10-20 16:52 UTC, ariasuni commented
It should be good now!! Plus I added integration tests.

2023-10-20 16:57 UTC, PThorpe92 approved these changes

2023-10-22 14:28 UTC, cafkafk approved these changes
Nice, looks good to me, and thanks for adding tests :heart:

2023-10-22 14:28 UTC, merged