feat(flags): Add BSD file flags
eza-community/eza pull request #701
Opened 2023-12-01 07:50 UTC by cfxegbert

Add BSD file flags.  See the man page for chflags(1).

2023-12-01 07:51 UTC, cfxegbert commented on src/options/help.rs
> +  -O, --flags                list file flags (Mac and BSD only)
Used `-O` because the is was Mac ls uses.

2023-12-01 17:48 UTC, MartinFillon requested changes
This needs some screens to show behaviour

2023-12-01 22:54 UTC, cfxegbert commented
> This needs some screens to show behaviour

```
target/debug/eza -lOh .                                                                                                       ─╯
Permissions Size User   Flags         Date Modified Name
drwxr-xr-x@    - rminsk -             27 Sep 15:56  benches
.rw-r--r--@ 3.9k rminsk -             27 Sep 15:56  build.rs
.rw-r--r--@  43k rminsk -             30 Nov 23:44  Cargo.lock
.rw-r--r--@ 3.2k rminsk -             30 Nov 23:44  Cargo.toml
.rw-r--r--@  30k rminsk -             30 Nov 23:44  CHANGELOG.md
.rw-r--r--@ 2.5k rminsk -              1 Nov 22:21  cliff.toml
.rw-r--r--@ 5.5k rminsk -             28 Aug 17:46  CODE_OF_CONDUCT.md
drwxr-xr-x@    - rminsk -              1 Nov 22:21  completions
.rw-r--r--@ 8.1k rminsk -             18 Nov 21:20  CONTRIBUTING.md
.rw-r--r--@ 1.7k rminsk -             28 Aug 17:46  deb.asc
.rw-r--r--@  12k rminsk -             19 Sep 22:08  deny.toml
drwxr-xr-x@    - rminsk -             18 Nov 21:20  devtools
drwxr-xr-x@    - rminsk -             18 Nov 21:20  docs
.rw-r--r--@ 7.8k rminsk -             18 Nov 21:20  flake.lock
.rw-r--r--@ 9.0k rminsk -             18 Nov 21:20  flake.nix
drwxr-xr-x@    - rminsk nodump        19 Nov 23:16  foo
drwxr-xr-x@    - rminsk nodump,hidden  7 Sep 19:44  hidden
```

2023-12-01 23:12 UTC, MartinFillon requested changes
The implementation is good on my side but waiting for @cafkafk answer regarding bsd action on element

2023-12-03 01:44 UTC, cfxegbert commented
Adding support for Windows attributes.  I will need someone else to test it.

2023-12-03 14:39 UTC, MartinFillon commented
I can test this tell me when this is ready to test

2023-12-05 11:20 UTC, cafkafk commented
> The implementation is good on my side but waiting for @cafkafk answer regarding bsd action on element

not sure what you're referring to here, was this on matrix?

2023-12-05 14:58 UTC, MartinFillon commented
yes

2023-12-05 21:45 UTC, MartinFillon submitted a review, later dismissed
This works on windows 🟢

2023-12-12 07:52 UTC, cafkafk approved these changes
Code is spotless, and very neat. 

Only failing test was one for help which I regenerated.

This feature is very very cool, turns out non-linux users can have nice things too!

2023-12-12 07:59 UTC, merged