chore: migrate from ansiterm to nu_ansi_term
eza-community/eza pull request #744
Opened 2023-12-25 21:29 UTC by PThorpe92

`nu_ansi_term` has a few features we could use including built-in [hyperlinks](https://docs.rs/nu-ansi-term/latest/nu_ansi_term/struct.AnsiGenericString.html#method.hyperlink) and [color-gradients](https://docs.rs/nu-ansi-term/latest/nu_ansi_term/gradient/struct.Gradient.html) that could move some of the work we currently do in `eza`.

This PR just migrates us to the dependency, it doesn't move any features over just yet.

2023-12-25 21:31 UTC, MartinFillon commented
gonna take a look tomorrow or later tonight but this is a great advancement

2023-12-26 22:10 UTC, PThorpe92 commented
Forgot to mention, the reason this didn't work out last attempt was that part of `color-scale` had to get re-implemented. I honestly thought it might break more stuff, but initial testing looked fine. The `color-scale` will have to be tested more thoroughly as I am not 100% on my fix.

2023-12-27 12:53 UTC, MartinFillon commented
gonna wait for the tests to pass

2023-12-27 16:11 UTC, PThorpe92 commented
wtf.. I had handled a merge conflict in the GH ui, but it must not have been fully committed or something because i pulled `main` into the branch and resolved it locally now all the tests pass. weird

2023-12-27 16:16 UTC, MartinFillon commented
> I had handled a merge conflict in the GH ui

Well such a simple error, never use gh ui xd

2023-12-27 16:19 UTC, MartinFillon submitted a review, later dismissed
This is a great start when merged it will surely open many options

2023-12-27 16:19 UTC, MartinFillon commented on src/main.rs
> -
nice loosing this boilerplate

2023-12-28 00:22 UTC, PThorpe92 commented
I just realized we are going to have to enable feature flag for windows. Gonna set it up for compilation dependent :+1:

2024-02-08 14:26 UTC, PThorpe92 commented
Config file is almost ready for PR. It will be dependent on `nu_ansi_term` so we should think about getting this merged pretty soon :+1:

2024-03-03 14:53 UTC, cafkafk requested changes
Can you resolve the conflicts, I'll review after :+1:

2024-03-27 06:44 UTC, cafkafk commented
Superseded by #910

2024-03-27 06:44 UTC, closed without merging