Clap cleanup
eza-community/eza pull request #822
Opened 2024-02-05 16:13 UTC by tertsdiepraam

Hi! I took some time to clean up the clap parser implementation. The most important change is that I changed the `u8`s to `bool`s and removed `ArgAction::Count`, because that felt a bit non-sensical. Other cleanups:
- Change the type of the help field
- Use a derive macro for `Default` on `Opts`
- Remove explicit names for long options
- Remove a bunch on unused types and methods (i.e. some that were only used in tests or not at all)
- Clean up the `ValueEnum` implementations a bit.

They can all be reviewed in separate commits and I can take commits out if you want.

2024-02-05 21:19 UTC, MartinFillon requested changes
Hey, Thanks for the heads up, for your information, the use of `u8` is justified
This is to prevent cases such as `ls -l` where `alias ls=eza --long` to fail, please revert this part of your commit. As this is an important feature to have and not to break.

If you want the full convo about this please see the closed clap prs

2024-02-05 21:19 UTC, MartinFillon commented on src/options/parser.rs
> +        alias = "octal-permissions"
This must be put in the documentation too.

2024-02-05 21:33 UTC, tertsdiepraam commented
Thanks for checking it out!

> If you want the full convo about this please see the closed clap prs

This convo or is there more context somewhere? https://github.com/eza-community/eza/pull/640#discussion_r1405381972

I'd still suggest using `args_override_self` instead of the `u8`s. I'll let the maintainers weigh in on this and I'll follow their decision. I'll also add tests for this behaviour regardless of the implementation we decide on.

2024-02-05 21:42 UTC, PThorpe92 commented
> Hey, Thanks for the heads up, for your information, the use of `u8` is justified This is to prevent cases such as `ls -l` where `alias ls=eza --long` to fail, please revert this part of your commit. As this is an important feature to have and not to break.
> 
> If you want the full convo about this please see the closed clap prs

Ok so lets have a convo about it. So you're saying the reason it was u8 instead of bool, was because if it gets passed twice, such as when it's already `--long` in the users alias, and again on the command line. 

@tertsdiepraam  was that behavior something a boolean flag could deal with/was that accounted for? I briefly remember it being brought up in the original PR

2024-02-05 22:51 UTC, MartinFillon commented
> I'd still suggest using args_override_self instead of the u8s. 

Seems perfect tbh

2024-02-05 23:02 UTC, tertsdiepraam commented
Awesome, I'll try to implement it!

2024-02-06 07:48 UTC, MartinFillon approved these changes
Thanks for the tests, and the documentation, LGTM.

2024-02-14 14:41 UTC, merged