Fix: NetBSD did not have fflagstostr and as such did not build properly
eza-community/eza pull request #868
Opened 2024-02-29 22:53 UTC by naguam

The NetBSD pkgsrc version just disabled the feature.

Fix implemented on the recommentation of the comment on http://cvsweb.netbsd.org/bsdweb.cgi/pkgsrc/sysutils/eza/patches/patch-src_output_render_mod.rs

Renamed the rust flags_to_string into wrapper_flags_to_string to avoid overlap with the extern C import which had the same name.

Now NetBSD file flags are supported and the build does not fail anymore.

2024-03-01 08:17 UTC, daviessm approved these changes
Looks sensible enough to me and all the tests pass!

Can you squash the commits and force-push to tidy up the commit history?

2024-03-01 08:18 UTC, fraggerfox commented
@naguam : I ran the build of eza with the changes you made in NetBSD (9.3) and I can confirm the patch works correctly as expected.

2024-03-01 08:51 UTC, cafkafk requested changes
> Looks sensible enough to me and all the tests pass!
> 
> Can you squash the commits and force-push to tidy up the commit history?

while at it, please lowercase the `Fix: ` part of your commit summary :+1:

2024-03-03 11:58 UTC, cafkafk approved these changes
I haven't tested this on NetBSD, but it doesn't seem to introduce regressions on linux, and code looks sane, so LGTM :+1:

2024-03-03 12:00 UTC, merged